export const BasicPermissionsNodes = [
    { label: "Home Command (essentials.home)", key: "essentials.home" },
    { label: "Set Home Command (essentials.sethome)", key: "essentials.sethome" },
    { label: "Delete Home Command (essentials.delhome)", key: "essentials.delhome" },
    { label: "Spawn Command (essentials.spawn)", key: "essentials.spawn" },
    { label: "TPA Command (essentials.tpa)", key: "essentials.tpa" },
    { label: "TPA Accept Command (essentials.tpaccept)", key: "essentials.tpaccept" },
    { label: "TPA Deny Command (essentials.tpadeny)", key: "essentials.tpadeny" },
    { label: "TPA Cancel Command (essentials.tpacancel)", key: "essentials.tpacancel" },
    { label: "TPA Here Command (essentials.tpahere)", key: "essentials.tpahere" },
    { label: "Pay Command (essentials.pay)", key: "essentials.pay" },
    { label: "Money Command (essentials.money)", key: "essentials.money" },
    { label: "Withdraw Command (essentials.withdraw)", key: "essentials.withdraw" },
    { label: "Shop Command (essentials.shop)", key: "essentials.shop" },
    { label: "Sell Command (essentials.sell)", key: "essentials.sell" },
    { label: "Auction Command (essentials.auction)", key: "essentials.auction" },
    { label: "Back Command (essentials.back)", key: "essentials.back" },
    { label: "Menu Command (essentials.menu)", key: "essentials.menu" },
    { label: "Chat Color Formatting (essentials.chat.color)", key: "essentials.chat.color" },
    { label: "Fly Command (essentials.fly)", key: "essentials.fly" },
    { label: "Heal Command (essentials.heal)", key: "essentials.heal" },
    { label: "Feed Command (essentials.feed)", key: "essentials.feed" },
    { label: "God Command (essentials.god)", key: "essentials.god" },
    { label: "Clear Command (essentials.clear)", key: "essentials.clear" },
    { label: "Chest Shop Create (Selling) (chestshop.create.sell)", key: "chestshop.create.sell" },
    { label: "Chest Shop Create (Buying) (chestshop.create.buy)", key: "chestshop.create.buy" },
    { label: "Chest Shop Sell (chestshop.sell)", key: "chestshop.sell" },
    { label: "Chest Shop Buy (chestshop.buy)", key: "chestshop.buy" },
    { label: "Land Claim Command (land.claim)", key: "land.claim" },
    { label: "Land Unclaim Command (land.unclaim)", key: "land.unclaim" },
    { label: "Land Invite Command (land.invite)", key: "land.invite" },
    { label: "Land Kick Command (land.kick)", key: "land.kick" },
    { label: "Land Transfer Command (land.transfer)", key: "land.transfer" },
    { label: "Land Setting Command (land.setting)", key: "land.setting" }
];

export const AdminPermissionsNodes = [
    { label: "Admin Panel Command (admin.panel)", key: "admin.panel" },
    { label: "Ban Command (admin.ban)", key: "admin.ban" },
    { label: "Kick Command (admin.kick)", key: "admin.kick" },
    { label: "Mute Command (admin.mute)", key: "admin.mute" },
    { label: "View Reports (admin.reports)", key: "admin.reports" },
    { label: "Broadcast Command (admin.broadcast)", key: "admin.broadcast" },
    { label: "Floating Text Command (admin.floatingtext)", key: "admin.floatingtext" },
    { label: "Inventory See Command (admin.invsee)", key: "admin.invsee" },
    { label: "Manage Ranks Command (admin.ranks)", key: "admin.ranks" },
    { label: "Setting Command (admin.setting)", key: "admin.setting" },
    { label: "Shop Setting Command (admin.shopsetting)", key: "admin.shopsetting" },
    { label: "Land Setting Command (admin.landsetting)", key: "admin.landsetting" },
    { label: "Manage Economy (admin.economy)", key: "admin.economy" },
    { label: "Admin Teleport Command (admin.tp)", key: "admin.tp" },
    { label: "Admin Warp Command (admin.warp)", key: "admin.warp" },
    { label: "Gamemode Creative (admin.gm.c)", key: "admin.gm.c" },
    { label: "Gamemode Survival (admin.gm.s)", key: "admin.gm.s" },
    { label: "Gamemode Spectator (admin.gm.sp)", key: "admin.gm.sp" },
    { label: "Gamemode Adventure (admin.gm.a)", key: "admin.gm.a" }
];
